"""empty message

Revision ID: 9a3f3e94de09
Revises: 
Create Date: 2024-10-16 17:33:53.454681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9a3f3e94de09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('years_known', sa.Integer(), nullable=False),
    sa.Column('owes_me', sa.Boolean(), nullable=False),
    sa.Column('has_a_dog', sa.Boolean(), nullable=False),
    sa.Column('spouse_is_annoying', sa.Boolean(), nullable=False),
    sa.Column('met', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend')
    # ### end Alembic commands ###
